#include <logos_test.h>

#include <array>
#include <iomanip>
#include <sstream>

#include <QJsonArray>
#include <QByteArray>
#include <QJsonDocument>
#include <QJsonObject>

#include "palace_lez.h"

namespace palace_lez_test {

constexpr const char* kProgramId =
    "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20";
constexpr const char* kRootPda =
    "99e683e8adac1e4f591b42879ae3e6480414f644c3eda3b592da3d62d72853b3";
constexpr const char* kSigner =
    "6666666666666666666666666666666666666666666666666666666666666666";
constexpr const char* kRootBorsh =
    "00030010101010101010101010101010101010101010101010101010101010101010100600000050"
    "616c6163652020202020202020202020202020202020202020202020202020202020202020303030"
    "30303030303030303030303030303030303030303030303030303030303030303030303030303030"
    "30303030303030303030303030303030303030303040404040404040404040404040404040404040"
    "404040404040404040404040400c000000626166796d616e69666573740300000002000000010000"
    "000100000007000000000000000700000000000000";
constexpr const char* kRootBorshSha256 =
    "34e418e0b0f0b2650a2ecf567c8731bdd986b9b4f7e89fa56cd7f927111fdbc3";
// Generated by serde_json from the pinned indexer_service_protocol crate.
constexpr const char* kRustIndexerPublishJson =
    R"([{"Public":{"hash":"0202020202020202020202020202020202020202020202020202020202020202","message":{"program_id":"4wBqpZM9xaSheZzJSMawUKKwhdpChKbZ5eu5ky4Vigw","account_ids":["BMmFJfVBfV1X8u5VTvt71C84RixWBcC4ABCzc69sJq2r","7tj9biW3KRJ7EEWmVUGigHiouCTXhV2dzcyvwma7Cyu7"],"nonces":[0,1],"instruction_data":[4,1,2,4,2036752738]},"witness_set":{"signatures_and_public_keys":[["22222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222","AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI="]],"proof":null}}}])";

palace::PalaceLezBytes32 bytes(const std::uint8_t value)
{
    palace::PalaceLezBytes32 output{};
    output.fill(value);
    return output;
}

std::vector<palace::PalaceLezInstructionV3> allInstructions()
{
    using namespace palace;
    PalaceLezInitializeV3 initialize;
    initialize.palaceId = bytes(0x10U);
    initialize.title = "Palace";
    initialize.activeManifestCid = "bafypalacemanifest";
    initialize.ownerProfile = {"Alice", bytes(0x51U), 1U, std::string("bafyavatar")};
    initialize.ownerGrantId = bytes(0x11U);
    initialize.entryRoomId = bytes(0x31U);
    initialize.entryRoom =
        {"Atrium", "bafyatrium", "bafyatriumscript", PalaceLezVmProfileV3::IptScraeMvpV1};
    initialize.secondaryRoomId = bytes(0x32U);
    initialize.secondaryRoom =
        {"Lounge", "bafylounge", "bafyloungescript", PalaceLezVmProfileV3::IptScraeMvpV1};

    PalaceLezScopeV3 roomScope{PalaceLezScopeKindV3::Room, bytes(0x31U)};
    return {
        PalaceLezInstructionV3{initialize},
        PalaceLezInstructionV3{
            PalaceLezRegisterUserV3{1U, {"Bob", bytes(0x52U), 1U, std::nullopt}}},
        PalaceLezInstructionV3{
            PalaceLezUpdateUserProfileV3{2U, "Bobby", std::string("bafybobby")}},
        PalaceLezInstructionV3{PalaceLezRotateDeliveryKeyV3{3U, bytes(0x53U), 2U}},
        PalaceLezInstructionV3{PalaceLezPublishManifestV3{4U, "bafynewmanifest"}},
        PalaceLezInstructionV3{PalaceLezUpdateRoomV3{
            5U,
            bytes(0x11U),
            bytes(0x31U),
            {"Atrium 2", "bafyatrium2", "bafyatriumscript2",
             PalaceLezVmProfileV3::IptScraeMvpV1}}},
        PalaceLezInstructionV3{PalaceLezGrantCapabilityV3{
            6U, bytes(0x12U), bytes(0x22U), roomScope, 5U, false, 20U}},
        PalaceLezInstructionV3{PalaceLezRevokeCapabilityV3{7U, bytes(0x12U)}},
        PalaceLezInstructionV3{
            PalaceLezSetRoomLockedV3{8U, bytes(0x12U), bytes(0x31U), true}},
        PalaceLezInstructionV3{PalaceLezCreateUserBanV3{
            9U, bytes(0x12U), bytes(0x41U), bytes(0x23U), roomScope}},
        PalaceLezInstructionV3{PalaceLezCreateAssetBanV3{
            10U, bytes(0x12U), bytes(0x42U), "bafyblocked", roomScope}},
        PalaceLezInstructionV3{
            PalaceLezSetBanActiveV3{11U, bytes(0x12U), bytes(0x42U), false}},
        PalaceLezInstructionV3{PalaceLezCreateSharedStateV3{
            12U,
            bytes(0x12U),
            bytes(0x61U),
            bytes(0x31U),
            "door",
            {0xaaU, 0xbbU, 0xccU},
            bytes(0x71U)}},
        PalaceLezInstructionV3{PalaceLezUpdateSharedStateV3{
            13U,
            bytes(0x12U),
            bytes(0x61U),
            bytes(0x31U),
            2U,
            {0x01U, 0x02U},
            bytes(0x72U)}},
    };
}

std::string hash(const std::size_t ordinal)
{
    std::ostringstream stream;
    stream << std::hex << std::setfill('0') << std::setw(64) << ordinal + 1U;
    return stream.str();
}

std::vector<std::uint8_t> wordsLeBytes(const std::vector<std::uint32_t>& words)
{
    std::vector<std::uint8_t> output;
    output.reserve(words.size() * sizeof(std::uint32_t));
    for (const std::uint32_t word : words) {
        output.push_back(static_cast<std::uint8_t>(word & 0xffU));
        output.push_back(static_cast<std::uint8_t>((word >> 8U) & 0xffU));
        output.push_back(static_cast<std::uint8_t>((word >> 16U) & 0xffU));
        output.push_back(static_cast<std::uint8_t>((word >> 24U) & 0xffU));
    }
    return output;
}

std::string hexBytes(const std::vector<std::uint8_t>& bytes)
{
    static constexpr char digits[] = "0123456789abcdef";
    std::string output(bytes.size() * 2U, '0');
    for (std::size_t index = 0U; index < bytes.size(); ++index) {
        output[index * 2U] = digits[bytes[index] >> 4U];
        output[index * 2U + 1U] = digits[bytes[index] & 0x0fU];
    }
    return output;
}

std::vector<std::uint8_t> accountIdBytes(const std::vector<std::string>& accountIdsHex)
{
    std::vector<std::uint8_t> output;
    output.reserve(accountIdsHex.size() * 32U);
    for (const std::string& accountIdHex : accountIdsHex) {
        palace::PalaceLezBytes32 account{};
        if (!palace::PalaceLezCodec::parseBytes32Hex(accountIdHex, account))
            return {};
        output.insert(output.end(), account.begin(), account.end());
    }
    return output;
}

std::string submissionJson(const std::string& transactionHash)
{
    return "{\"success\":true,\"tx_hash\":\"" + transactionHash
        + "\",\"secrets\":[],\"error\":\"\"}";
}

std::string publicAccountJson(const std::string& dataHex)
{
    return "{\"program_owner\":\"" + std::string(kProgramId)
        + "\",\"balance\":\"00000000000000000000000000000000\","
          "\"nonce\":\"00000000000000000000000000000000\",\"data\":\""
        + dataHex + "\"}";
}

std::string rootAccountJson()
{
    return publicAccountJson(kRootBorsh);
}

QJsonObject indexerTransaction(
    const palace::PalaceLezTransactionPlanV3& plan,
    const std::string& transactionHash)
{
    palace::PalaceLezBytes32 programId{};
    LOGOS_ASSERT_TRUE(palace::PalaceLezCodec::parseBytes32Hex(
        plan.programIdHex,
        programId));
    QJsonObject message;
    message.insert(
        QStringLiteral("program_id"),
        QString::fromStdString(palace::PalaceLezCodec::accountIdBase58(programId)));
    QJsonArray accounts;
    QJsonArray nonces;
    for (const std::string& accountHex : plan.accountIdsHex) {
        palace::PalaceLezBytes32 account{};
        LOGOS_ASSERT_TRUE(palace::PalaceLezCodec::parseBytes32Hex(accountHex, account));
        accounts.append(
            QString::fromStdString(palace::PalaceLezCodec::accountIdBase58(account)));
        nonces.append(0);
    }
    message.insert(QStringLiteral("account_ids"), accounts);
    message.insert(QStringLiteral("nonces"), nonces);
    QJsonArray words;
    for (const std::uint32_t word : plan.instructionWords)
        words.append(static_cast<double>(word));
    message.insert(QStringLiteral("instruction_data"), words);

    QJsonArray signatures;
    for (const bool required : plan.signingRequirements) {
        if (!required)
            continue;
        QJsonArray pair;
        pair.append(QString(128U, QLatin1Char('1')));
        pair.append(QString::fromLatin1(QByteArray(32, '\x01').toBase64()));
        signatures.append(pair);
    }
    QJsonObject witness;
    witness.insert(QStringLiteral("signatures_and_public_keys"), signatures);
    witness.insert(QStringLiteral("proof"), QJsonValue::Null);

    QJsonObject transaction;
    transaction.insert(QStringLiteral("hash"), QString::fromStdString(transactionHash));
    transaction.insert(QStringLiteral("message"), message);
    transaction.insert(QStringLiteral("witness_set"), witness);
    QJsonObject tagged;
    tagged.insert(QStringLiteral("Public"), transaction);
    return tagged;
}

std::string indexerJson(
    const std::vector<std::pair<palace::PalaceLezTransactionPlanV3, std::string>>& values)
{
    QJsonArray transactions;
    for (const auto& value : values)
        transactions.append(indexerTransaction(value.first, value.second));
    return QJsonDocument(transactions).toJson(QJsonDocument::Compact).toStdString();
}

std::string indexerRpcJson(
    const std::vector<std::pair<palace::PalaceLezTransactionPlanV3, std::string>>& values)
{
    QJsonArray transactions;
    for (const auto& value : values)
        transactions.append(indexerTransaction(value.first, value.second));
    QJsonObject envelope;
    envelope.insert(QStringLiteral("jsonrpc"), QStringLiteral("2.0"));
    envelope.insert(QStringLiteral("result"), transactions);
    envelope.insert(QStringLiteral("id"), 1);
    return QJsonDocument(envelope).toJson(QJsonDocument::Compact).toStdString();
}

palace::PalaceLezNetworkFingerprint fingerprint()
{
    return {
        "lez-testnet",
        "0.4.0-alpha.2",
        "9e140c6d9529ee313d7bf4627677b4e7f552ab34",
        "6e0013f5b771fc1b96a65361b531f289111b8aaa",
        "0.2.0",
        "a58fbce2ff48c58b7bb5001b1a27e64b9596ee3a",
        kProgramId,
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    };
}

void makeCompatible(palace::PalaceLezTransactionCoordinator& coordinator)
{
    const palace::PalaceLezNetworkFingerprint value = fingerprint();
    const palace::PalaceLezCompatibilityResult compatibility =
        coordinator.configureNetworkFingerprint(value, value);
    LOGOS_ASSERT_TRUE(compatibility.accepted);
    LOGOS_ASSERT_TRUE(coordinator.activate());
}

} // namespace palace_lez_test

LOGOS_TEST(palace_lez_v3_matches_rust_serde_variable_and_fixed_field_fixtures) {
    using namespace palace;
    using namespace palace_lez_test;

    const PalaceLezInstructionV3 publish{
        PalaceLezPublishManifestV3{0x0000000200000001ULL, "bafy"}};
    const std::vector<std::uint32_t> expectedPublish{
        4U, 1U, 2U, 4U, 0x79666162U};
    LOGOS_ASSERT_TRUE(
        PalaceLezCodec::encodeInstruction(publish).words == expectedPublish);

    PalaceLezGrantCapabilityV3 grant;
    grant.orderedActionId = 6U;
    grant.grantId = bytes(0x11U);
    grant.subjectUserId = bytes(0x22U);
    grant.scope = {PalaceLezScopeKindV3::Room, bytes(0x33U)};
    grant.capabilities = 5U;
    grant.delegable = true;
    grant.validThroughActionId = 20U;
    std::vector<std::uint32_t> expectedGrant{6U, 6U, 0U};
    expectedGrant.insert(expectedGrant.end(), 32U, 0x11U);
    expectedGrant.insert(expectedGrant.end(), 32U, 0x22U);
    expectedGrant.push_back(1U);
    expectedGrant.insert(expectedGrant.end(), 32U, 0x33U);
    expectedGrant.insert(expectedGrant.end(), {5U, 1U, 20U, 0U});
    LOGOS_ASSERT_TRUE(
        PalaceLezCodec::encodeInstruction(PalaceLezInstructionV3{grant}).words ==
        expectedGrant);

    PalaceLezCreateSharedStateV3 shared{
        12U,
        bytes(0x11U),
        bytes(0x22U),
        bytes(0x33U),
        "door",
        {0xaaU, 0xbbU, 0xccU},
        bytes(0x44U)};
    std::vector<std::uint32_t> expectedShared{12U, 12U, 0U};
    expectedShared.insert(expectedShared.end(), 32U, 0x11U);
    expectedShared.insert(expectedShared.end(), 32U, 0x22U);
    expectedShared.insert(expectedShared.end(), 32U, 0x33U);
    expectedShared.insert(
        expectedShared.end(),
        {4U, 0x726f6f64U, 3U, 0xaaU, 0xbbU, 0xccU});
    expectedShared.insert(expectedShared.end(), 32U, 0x44U);
    LOGOS_ASSERT_TRUE(
        PalaceLezCodec::encodeInstruction(PalaceLezInstructionV3{shared}).words ==
        expectedShared);

    PalaceLezRegisterUserV3 profile{
        1U, {"Bob", bytes(0x55U), 9U, std::string("bafyavatar")}};
    std::vector<std::uint32_t> expectedProfile{1U, 1U, 0U, 3U, 0x00626f42U};
    expectedProfile.insert(expectedProfile.end(), 32U, 0x55U);
    expectedProfile.insert(
        expectedProfile.end(),
        {9U, 0U, 1U, 10U, 0x79666162U, 0x74617661U, 0x00007261U});
    LOGOS_ASSERT_TRUE(
        PalaceLezCodec::encodeInstruction(PalaceLezInstructionV3{profile}).words ==
        expectedProfile);
}

LOGOS_TEST(palace_lez_v3_round_trips_all_variants_and_exact_account_order) {
    using namespace palace;
    using namespace palace_lez_test;
    const std::array<std::size_t, 14> expectedAccountCounts{
        6U, 3U, 3U, 3U, 2U, 4U, 4U, 3U, 4U, 5U, 4U, 4U, 5U, 5U};
    // Generated with lee_core::AccountId::for_public_pda over the account
    // declarations in the Rust guest, then hashed in declared order.
    const std::array<const char*, 14> rustAccountOrderDigests{
        "c4a3b3c0aa25263764841020ac168280d3df8be7fd1ced2ac60825767e522c39",
        "8b6ba3bf4f388fa19452a7bd9442c2e3d4254d962bcfd8f07c064674006fb8d8",
        "8b6ba3bf4f388fa19452a7bd9442c2e3d4254d962bcfd8f07c064674006fb8d8",
        "8b6ba3bf4f388fa19452a7bd9442c2e3d4254d962bcfd8f07c064674006fb8d8",
        "ab3362ddd55db987954daa2741559c0c498786032f163bb4df5dcc58bb9b8ba4",
        "2e9f1a2b5ef170fad71f049f56210d9fea4e17ce3bdc8142e38a4f77aca954b1",
        "bed9240fdaf03a158fe7f58ffe14f7a1642a242d7aa6454a6ea7577d961fcfdd",
        "1da37229915e72e973d594c9c54a50603e11708f5523617cd7065da04b973fdb",
        "9e5727e9e30397e71e9aebd748508eefc255ee728cbc2cf87f365d9e79ebdd3f",
        "dbd658629c00d5beffe50b9a88d0e6c9891aeffe11bcf67ea18e5fe1427a500c",
        "56b6859ffd4ba3a45ab2baf3389c8c8664875b36e3ba2cc7c96ef63da58a536e",
        "56b6859ffd4ba3a45ab2baf3389c8c8664875b36e3ba2cc7c96ef63da58a536e",
        "6c303f9a5b3f0d4aca582100d7028bc70e4cea8fbb71aec82d73183a60509702",
        "6c303f9a5b3f0d4aca582100d7028bc70e4cea8fbb71aec82d73183a60509702"};
    // Generated by risc0_zkvm::serde::to_vec over the matching Rust
    // GuestInstruction values, then SHA-256 over little-endian u32 words.
    const std::array<std::size_t, 14> rustWordCounts{
        206U, 40U, 11U, 37U, 8U, 81U, 104U, 35U, 68U, 132U, 104U, 68U,
        137U, 136U};
    const std::array<const char*, 14> rustWordDigests{
        "1a2c55bbff19197565d121629557a43e855beb992c109ed082cd499e8e603134",
        "558b5308c589549e2fd9385bc212ff764abfbcfe5f81b5a5ed16947f9e7ae55c",
        "0fa76d7d36ce6cf1461841537696e48596c2808e99301600e91b7828b03d59df",
        "f18c9818e388bf449e71e4220bb409da7b2a78bba697a1f06881d6a23fde892a",
        "864b2cd7e269b8a6b2b6fab2297fff91e8d32a55529a7f89e92f1518207faf2f",
        "d36a736b14a428265e2d82fda99c09b0aa3668e8ac02190b7eb0d3bdee8f6a5f",
        "97e4a4b87922cbb11a010711cc391f8a6823b95ebda89dc55fbc4c213dae430e",
        "b94bd864a1adcd488b2c3ba60ddd9a9586b8a7200b48d780a335da0e23a10711",
        "2c20fc67bb9509824f878c371fa61153ff53769ffb92bf6eb15b29e4c56cbdb0",
        "cec4f0c9452ea09d4ff0b17836f4b72a08cb17dcf80fe948674c121b1926f0d7",
        "66bd88c21050b87496107b7fb5ac2863c095022de9a51ff2c5314a178c6b8828",
        "138aa85b9905fffef7f8d9a976d561c9e9d440eaccb9e8c4807017af96c85b9f",
        "cc5b15fcaf23fb9970f86d209a4268f8eb0942d386dedcd85141642459a662b5",
        "9ff065111d64371aab2641eb3f205621cbbf7460952d48ac6ed7558a31d4a612"};
    const std::vector<PalaceLezInstructionV3> instructions = allInstructions();
    LOGOS_ASSERT_EQ(instructions.size(), expectedAccountCounts.size());
    for (std::size_t index = 0; index < instructions.size(); ++index) {
        const PalaceLezWireInstruction encoded =
            PalaceLezCodec::encodeInstruction(instructions[index]);
        LOGOS_ASSERT_TRUE(encoded.accepted);
        LOGOS_ASSERT_EQ(encoded.words.size(), rustWordCounts[index]);
        LOGOS_ASSERT_EQ(
            PalaceLezCodec::sha256Hex(wordsLeBytes(encoded.words)),
            std::string(rustWordDigests[index]));
        const PalaceLezWireInstruction decoded =
            PalaceLezCodec::decodeInstruction(encoded.words);
        LOGOS_ASSERT_TRUE(decoded.accepted);
        LOGOS_ASSERT_EQ(decoded.instruction.payload.index(), index);
        LOGOS_ASSERT_TRUE(
            PalaceLezCodec::encodeInstruction(decoded.instruction).words ==
            encoded.words);

        const PalaceLezTransactionPlanV3 plan =
            PalaceLezCodec::buildTransaction(kProgramId, kSigner, instructions[index]);
        LOGOS_ASSERT_TRUE(plan.accepted);
        LOGOS_ASSERT_EQ(plan.rootAccountIdHex, std::string(kRootPda));
        LOGOS_ASSERT_EQ(plan.accountIdsHex.size(), expectedAccountCounts[index]);
        LOGOS_ASSERT_EQ(plan.accountIdsHex.front(), std::string(kRootPda));
        LOGOS_ASSERT_EQ(plan.accountIdsHex.at(1), std::string(kSigner));
        LOGOS_ASSERT_EQ(
            PalaceLezCodec::sha256Hex(accountIdBytes(plan.accountIdsHex)),
            std::string(rustAccountOrderDigests[index]));
        LOGOS_ASSERT_EQ(plan.signingRequirements.size(), plan.accountIdsHex.size());
        for (std::size_t account = 0; account < plan.signingRequirements.size(); ++account)
            LOGOS_ASSERT_TRUE(
                static_cast<bool>(plan.signingRequirements[account]) ==
                (account == 1U));
    }
}

LOGOS_TEST(palace_lez_v3_matches_rust_pda_derivation_and_base58_canonical_form) {
    using namespace palace;
    using namespace palace_lez_test;
    LOGOS_ASSERT_EQ(PalaceLezCodec::deriveRootPda(kProgramId), std::string(kRootPda));
    LOGOS_ASSERT_EQ(
        PalaceLezCodec::deriveRecordPda(kProgramId, "profile", kRootPda, bytes(0x77U)),
        std::string("576e1edc6b90e79e8a89487812115542e5209548051131444c2847b2a1dbb9da"));

    PalaceLezBytes32 account{};
    LOGOS_ASSERT_TRUE(PalaceLezCodec::parseBytes32Hex(kRootPda, account));
    const std::string base58 = PalaceLezCodec::accountIdBase58(account);
    PalaceLezBytes32 restored{};
    LOGOS_ASSERT_TRUE(PalaceLezCodec::parseAccountIdBase58(base58, restored));
    LOGOS_ASSERT_TRUE(restored == account);
    LOGOS_ASSERT_FALSE(PalaceLezCodec::parseAccountIdBase58(base58 + "0", restored));
    LOGOS_ASSERT_FALSE(PalaceLezCodec::parseBytes32Hex(std::string(64U, 'A'), restored));
}

LOGOS_TEST(palace_lez_v3_decodes_strict_rust_borsh_record_not_serde_words) {
    using namespace palace;
    using namespace palace_lez_test;
    const PalaceLezPublicAccountV3 account =
        PalaceLezCodec::decodePublicAccount(rootAccountJson(), kProgramId);
    LOGOS_ASSERT_TRUE(account.accepted);
    LOGOS_ASSERT_EQ(
        static_cast<std::uint8_t>(account.recordType),
        static_cast<std::uint8_t>(PalaceLezRecordTypeV3::PalaceRoot));
    LOGOS_ASSERT_EQ(account.dataSha256Hex, std::string(kRootBorshSha256));
    const PalaceLezRootRecordV3* root = std::get_if<PalaceLezRootRecordV3>(&account.record);
    LOGOS_ASSERT_TRUE(root != nullptr);
    LOGOS_ASSERT_EQ(root->title, std::string("Palace"));
    LOGOS_ASSERT_EQ(root->lastOrderedActionId, 7U);
    LOGOS_ASSERT_TRUE(root->roomIds[0] == bytes(0x30U));
    LOGOS_ASSERT_TRUE(root->roomIds[1] == bytes(0x40U));

    std::string trailing = rootAccountJson();
    trailing.replace(trailing.size() - 2U, 2U, "00\"}");
    const PalaceLezPublicAccountV3 invalid =
        PalaceLezCodec::decodePublicAccount(trailing, kProgramId);
    LOGOS_ASSERT_FALSE(invalid.accepted);
    LOGOS_ASSERT_EQ(invalid.reason, std::string("trailing-record-data"));

    std::string wrongSchema = rootAccountJson();
    const std::size_t data = wrongSchema.find(kRootBorsh);
    LOGOS_ASSERT_TRUE(data != std::string::npos);
    wrongSchema.replace(data + 2U, 4U, "0200");
    const PalaceLezPublicAccountV3 unsupported =
        PalaceLezCodec::decodePublicAccount(wrongSchema, kProgramId);
    LOGOS_ASSERT_FALSE(unsupported.accepted);
    LOGOS_ASSERT_EQ(unsupported.reason, std::string("unsupported-schema"));
}

LOGOS_TEST(palace_lez_v3_parses_generic_account_snapshots_without_schema_confusion) {
    using namespace palace;
    using namespace palace_lez_test;

    const std::string empty =
        "{\"nonce\":\"00000000000000000000000000000000\","
        "\"data\":\"\","
        "\"program_owner\":\"" + std::string(kSigner) + "\","
        "\"balance\":\"00000000000000000000000000000000\"}";
    const PalaceLezRawAccountV1 parsed =
        PalaceLezCodec::parsePublicAccountSnapshot(empty);
    LOGOS_ASSERT_TRUE(parsed.accepted);
    LOGOS_ASSERT_TRUE(parsed.data.empty());
    LOGOS_ASSERT_EQ(
        parsed.dataSha256Hex,
        std::string("e3b0c44298fc1c149afbf4c8996fb924"
                    "27ae41e4649b934ca495991b7852b855"));

    std::string bytesJson = empty;
    bytesJson.replace(bytesJson.find("\"data\":\"\""), 9U, "\"data\":\"00ff\"");
    const PalaceLezRawAccountV1 withBytes =
        PalaceLezCodec::parsePublicAccountSnapshot(bytesJson);
    LOGOS_ASSERT_TRUE(withBytes.accepted);
    LOGOS_ASSERT_TRUE(
        withBytes.data == std::vector<std::uint8_t>({0x00U, 0xffU}));

    const std::string duplicate =
        "{\"program_owner\":\"" + std::string(kSigner) + "\","
        "\"progra\\u006d_owner\":\"" + std::string(kSigner) + "\","
        "\"balance\":\"00000000000000000000000000000000\","
        "\"nonce\":\"00000000000000000000000000000000\","
        "\"data\":\"\"}";
    const PalaceLezRawAccountV1 duplicateResult =
        PalaceLezCodec::parsePublicAccountSnapshot(duplicate);
    LOGOS_ASSERT_FALSE(duplicateResult.accepted);
    LOGOS_ASSERT_EQ(duplicateResult.reason, std::string("duplicate-json-key"));

    const PalaceLezRawAccountV1 extra =
        PalaceLezCodec::parsePublicAccountSnapshot(
            empty.substr(0U, empty.size() - 1U) + ",\"extra\":\"00\"}");
    LOGOS_ASSERT_FALSE(extra.accepted);
    LOGOS_ASSERT_EQ(extra.reason, std::string("invalid-account-response"));

    std::string uppercase = bytesJson;
    uppercase.replace(uppercase.find("00ff"), 4U, "00FF");
    const PalaceLezRawAccountV1 uppercaseResult =
        PalaceLezCodec::parsePublicAccountSnapshot(uppercase);
    LOGOS_ASSERT_FALSE(uppercaseResult.accepted);
    LOGOS_ASSERT_EQ(uppercaseResult.reason, std::string("invalid-account-data"));
}

LOGOS_TEST(palace_lez_v3_predicts_exact_rust_root_bytes_and_bounded_advances) {
    using namespace palace;
    using namespace palace_lez_test;

    const PalaceLezPublicAccountV3 decoded =
        PalaceLezCodec::decodePublicAccount(rootAccountJson(), kProgramId);
    LOGOS_ASSERT_TRUE(decoded.accepted);
    const PalaceLezRootRecordV3* root =
        std::get_if<PalaceLezRootRecordV3>(&decoded.record);
    LOGOS_ASSERT_TRUE(root != nullptr);
    const std::vector<std::uint8_t> exact =
        PalaceLezCodec::encodeRootRecord(*root);
    LOGOS_ASSERT_EQ(hexBytes(exact), std::string(kRootBorsh));
    LOGOS_ASSERT_EQ(
        PalaceLezCodec::sha256Hex(exact),
        std::string(kRootBorshSha256));

    const PalaceLezExpectedRootV3 advanced =
        PalaceLezCodec::expectedAdvancedRoot(
            *root,
            PalaceLezInstructionV3{
                PalaceLezPublishManifestV3{8U, "bafynewmanifest"}});
    LOGOS_ASSERT_TRUE(advanced.accepted);
    LOGOS_ASSERT_EQ(advanced.record.revision, 8U);
    LOGOS_ASSERT_EQ(advanced.record.lastOrderedActionId, 8U);
    LOGOS_ASSERT_EQ(
        advanced.record.activeManifestCid,
        std::string("bafynewmanifest"));
    LOGOS_ASSERT_EQ(
        advanced.dataSha256Hex,
        PalaceLezCodec::sha256Hex(advanced.encodedRecord));
    const PalaceLezPublicAccountV3 roundTrip =
        PalaceLezCodec::decodePublicAccount(
            publicAccountJson(hexBytes(advanced.encodedRecord)),
            kProgramId);
    LOGOS_ASSERT_TRUE(roundTrip.accepted);
    LOGOS_ASSERT_FALSE(
        PalaceLezCodec::expectedAdvancedRoot(
            *root,
            PalaceLezInstructionV3{
                PalaceLezPublishManifestV3{9U, "bafygap"}})
            .accepted);

    const PalaceLezInstructionV3 initialize = allInstructions().front();
    const PalaceLezExpectedRootV3 initial =
        PalaceLezCodec::expectedInitialRoot(kSigner, initialize);
    LOGOS_ASSERT_TRUE(initial.accepted);
    LOGOS_ASSERT_TRUE(initial.record.owner == bytes(0x66U));
    LOGOS_ASSERT_EQ(initial.record.userCount, 1U);
    LOGOS_ASSERT_EQ(initial.record.grantCount, 1U);
    LOGOS_ASSERT_EQ(initial.record.revision, 0U);
    LOGOS_ASSERT_EQ(initial.record.lastOrderedActionId, 0U);
}

LOGOS_TEST(palace_lez_v3_decodes_every_rust_borsh_record_shape) {
    using namespace palace;
    using namespace palace_lez_test;
    struct Fixture {
        PalaceLezRecordTypeV3 type;
        const char* dataHex;
        const char* digestHex;
    };
    const std::array<Fixture, 6> fixtures{{
        {PalaceLezRecordTypeV3::UserProfile,
         "010300101010101010101010101010101010101010101010101010101010101010101021212121"
         "2121212121212121212121212121212121212121212121212121212103000000426f6251515151"
         "515151515151515151515151515151515151515151515151515151510200000000000000010a00"
         "0000626166796176617461720300000000000000",
         "5a9af840840c19c0c53e2f042bba33ac2aa4e57bf238b9f7bbb633ef11da3294"},
        {PalaceLezRecordTypeV3::Room,
         "020300101010101010101010101010101010101010101010101010101010101010101031313131"
         "313131313131313131313131313131313131313131313131313131310600000041747269756d0a"
         "0000006261667961747269756d100000006261667961747269756d73637269707401010400000000"
         "000000",
         "df2a354083761aa2dfedfdcb8ae5bf3ea68b6407b266313f5548e8b712e1845d"},
        {PalaceLezRecordTypeV3::CapabilityGrant,
         "03030010101010101010101010101010101010101010101010101010101010101010101111111111"
         "11111111111111111111111111111111111111111111111111111121212121212121212121212121"
         "21212121212121212121212121212121212121222222222222222222222222222222222222222222"
         "22222222222222222222220131313131313131313131313131313131313131313131313131313131"
         "3131313105000000011400000000000000000200000000000000",
         "110fa2ad5af99366389b4fe28107a16556c9c74061ef92ce2fc8c076d618eb78"},
        {PalaceLezRecordTypeV3::Ban,
         "04030010101010101010101010101010101010101010101010101010101010101010104141414141"
         "41414141414141414141414141414141414141414141414141414100212121212121212121212121"
         "21212121212121212121212121212121212121212222222222222222222222222222222222222222"
         "22222222222222222222222200010100000000000000",
         "cef3a71ce21a0d539737a2f784586ec79de47c16404884b53f9336c762beff42"},
        {PalaceLezRecordTypeV3::Ban,
         "040300101010101010101010101010101010101010101010101010101010101010101042424242"
         "42424242424242424242424242424242424242424242424242424242010b00000062616679626c"
         "6f636b656422222222222222222222222222222222222222222222222222222222222222220131"
         "313131313131313131313131313131313131313131313131313131313131310002000000000000"
         "00",
         "a622be99be29e6aad900b59cc2204de16d465d06bc5039196d23d36d05491ab9"},
        {PalaceLezRecordTypeV3::RoomSharedState,
         "050300101010101010101010101010101010101010101010101010101010101010101061616161"
         "61616161616161616161616161616161616161616161616161616161313131313131313131313131"
         "313131313131313131313131313131313131313104000000646f6f7203000000aabbcc71717171"
         "7171717171717171717171717171717171717171717171717171717102000000000000000c000000"
         "00000000",
         "fb881a8ca4b2a9de876fa22f36c65ace37af1045396bd34715a119576fe0f4f4"},
    }};

    std::vector<PalaceLezPublicAccountV3> decoded;
    decoded.reserve(fixtures.size());
    for (const Fixture& fixture : fixtures) {
        decoded.push_back(PalaceLezCodec::decodePublicAccount(
            publicAccountJson(fixture.dataHex),
            kProgramId));
        LOGOS_ASSERT_TRUE(decoded.back().accepted);
        LOGOS_ASSERT_EQ(
            static_cast<std::uint8_t>(decoded.back().recordType),
            static_cast<std::uint8_t>(fixture.type));
        LOGOS_ASSERT_EQ(decoded.back().dataSha256Hex, std::string(fixture.digestHex));
    }

    const PalaceLezUserProfileRecordV3* profile =
        std::get_if<PalaceLezUserProfileRecordV3>(&decoded[0].record);
    LOGOS_ASSERT_TRUE(profile != nullptr);
    LOGOS_ASSERT_EQ(profile->displayName, std::string("Bob"));
    LOGOS_ASSERT_TRUE(profile->avatarManifestCid == std::optional<std::string>("bafyavatar"));
    const PalaceLezRoomRecordV3* room =
        std::get_if<PalaceLezRoomRecordV3>(&decoded[1].record);
    LOGOS_ASSERT_TRUE(room != nullptr);
    LOGOS_ASSERT_TRUE(room->locked);
    LOGOS_ASSERT_EQ(room->revision, 4U);
    const PalaceLezCapabilityGrantRecordV3* grant =
        std::get_if<PalaceLezCapabilityGrantRecordV3>(&decoded[2].record);
    LOGOS_ASSERT_TRUE(grant != nullptr);
    LOGOS_ASSERT_EQ(grant->capabilities, 5U);
    LOGOS_ASSERT_TRUE(grant->delegable);
    const PalaceLezBanRecordV3* userBan =
        std::get_if<PalaceLezBanRecordV3>(&decoded[3].record);
    const PalaceLezBanRecordV3* assetBan =
        std::get_if<PalaceLezBanRecordV3>(&decoded[4].record);
    LOGOS_ASSERT_TRUE(userBan != nullptr);
    LOGOS_ASSERT_TRUE(assetBan != nullptr);
    LOGOS_ASSERT_EQ(
        static_cast<std::uint8_t>(userBan->targetKind),
        static_cast<std::uint8_t>(PalaceLezBanTargetKindV3::User));
    LOGOS_ASSERT_EQ(assetBan->targetAssetCid, std::string("bafyblocked"));
    const PalaceLezRoomSharedStateRecordV3* shared =
        std::get_if<PalaceLezRoomSharedStateRecordV3>(&decoded[5].record);
    LOGOS_ASSERT_TRUE(shared != nullptr);
    LOGOS_ASSERT_EQ(shared->key, std::string("door"));
    LOGOS_ASSERT_EQ(shared->lastOrderedActionId, 12U);
    LOGOS_ASSERT_TRUE(shared->value == std::vector<std::uint8_t>({0xaaU, 0xbbU, 0xccU}));
}

LOGOS_TEST(palace_lez_v3_rejects_word_padding_bounds_and_malformed_json) {
    using namespace palace;
    PalaceLezInstructionV3 publish{PalaceLezPublishManifestV3{1U, "bafy1"}};
    PalaceLezWireInstruction encoded = PalaceLezCodec::encodeInstruction(publish);
    LOGOS_ASSERT_TRUE(encoded.accepted);
    encoded.words.back() |= 0xff000000U;
    LOGOS_ASSERT_FALSE(PalaceLezCodec::decodeInstruction(encoded.words).accepted);

    PalaceLezCreateSharedStateV3 oversized;
    oversized.orderedActionId = 1U;
    oversized.grantId = palace_lez_test::bytes(1U);
    oversized.sharedStateId = palace_lez_test::bytes(2U);
    oversized.roomId = palace_lez_test::bytes(3U);
    oversized.key = "door";
    oversized.value.assign(513U, 1U);
    oversized.stateRoot = palace_lez_test::bytes(4U);
    LOGOS_ASSERT_FALSE(
        PalaceLezCodec::encodeInstruction(PalaceLezInstructionV3{oversized}).accepted);

    LOGOS_ASSERT_FALSE(PalaceLezCodec::parseFinalizedTransactions("{").accepted);
    LOGOS_ASSERT_FALSE(PalaceLezCodec::decodePublicAccount(
        "{\"program_owner\":1}",
        palace_lez_test::kProgramId).accepted);
}

LOGOS_TEST(palace_lez_v3_rebuilds_only_strict_chronological_finalized_history) {
    using namespace palace;
    using namespace palace_lez_test;
    const std::vector<PalaceLezInstructionV3> instructions = allInstructions();
    std::vector<std::pair<PalaceLezTransactionPlanV3, std::string>> indexed;
    for (std::size_t index = 0; index < instructions.size(); ++index) {
        indexed.push_back(
            {PalaceLezCodec::buildTransaction(kProgramId, kSigner, instructions[index]),
             hash(index)});
        LOGOS_ASSERT_TRUE(indexed.back().first.accepted);
    }
    const PalaceLezRebuildResultV3 rebuilt =
        PalaceLezCodec::rebuildFinalizedHistory(
            kProgramId,
            kRootPda,
            indexerJson(indexed));
    LOGOS_ASSERT_TRUE(rebuilt.accepted);
    LOGOS_ASSERT_EQ(rebuilt.actions.size(), instructions.size());
    for (std::size_t index = 0; index < rebuilt.actions.size(); ++index)
        LOGOS_ASSERT_EQ(rebuilt.actions[index].orderedActionId, index);

    std::swap(indexed[1], indexed[2]);
    const PalaceLezRebuildResultV3 reordered =
        PalaceLezCodec::rebuildFinalizedHistory(
            kProgramId,
            kRootPda,
            indexerJson(indexed));
    LOGOS_ASSERT_FALSE(reordered.accepted);
    LOGOS_ASSERT_EQ(
        reordered.reason,
        std::string("non-chronological-finalized-history"));
}

LOGOS_TEST(palace_lez_v3_indexer_parser_rejects_malformed_base58_and_bytes) {
    using namespace palace;
    using namespace palace_lez_test;
    const PalaceLezIndexerParseResult rustFixture =
        PalaceLezCodec::parseFinalizedTransactions(kRustIndexerPublishJson);
    LOGOS_ASSERT_TRUE(rustFixture.accepted);
    LOGOS_ASSERT_EQ(rustFixture.transactions.size(), 1U);
    LOGOS_ASSERT_EQ(rustFixture.transactions[0].programIdHex, std::string(kProgramId));
    LOGOS_ASSERT_EQ(rustFixture.transactions[0].accounts.size(), 2U);
    LOGOS_ASSERT_EQ(rustFixture.transactions[0].accounts[0].accountIdHex, std::string(kRootPda));
    LOGOS_ASSERT_EQ(rustFixture.transactions[0].accounts[0].nonce, std::string("0"));
    LOGOS_ASSERT_EQ(rustFixture.transactions[0].accounts[1].accountIdHex, std::string(kSigner));
    LOGOS_ASSERT_EQ(rustFixture.transactions[0].accounts[1].nonce, std::string("1"));
    LOGOS_ASSERT_TRUE(
        rustFixture.transactions[0].instructionWords
        == std::vector<std::uint32_t>({4U, 1U, 2U, 4U, 2036752738U}));
    LOGOS_ASSERT_EQ(rustFixture.transactions[0].signatureCount, 1U);

    const PalaceLezTransactionPlanV3 plan =
        PalaceLezCodec::buildTransaction(kProgramId, kSigner, allInstructions().front());
    QJsonObject transaction = indexerTransaction(plan, hash(0U));
    QJsonObject publicTransaction =
        transaction.value(QStringLiteral("Public")).toObject();
    QJsonObject message =
        publicTransaction.value(QStringLiteral("message")).toObject();
    QJsonArray accounts = message.value(QStringLiteral("account_ids")).toArray();
    accounts.replace(0, QStringLiteral("0invalid"));
    message.insert(QStringLiteral("account_ids"), accounts);
    publicTransaction.insert(QStringLiteral("message"), message);
    transaction.insert(QStringLiteral("Public"), publicTransaction);
    QJsonArray list;
    list.append(transaction);
    LOGOS_ASSERT_FALSE(PalaceLezCodec::parseFinalizedTransactions(
        QJsonDocument(list).toJson(QJsonDocument::Compact).toStdString()).accepted);

    transaction = indexerTransaction(plan, hash(0U));
    publicTransaction = transaction.value(QStringLiteral("Public")).toObject();
    message = publicTransaction.value(QStringLiteral("message")).toObject();
    QJsonArray words = message.value(QStringLiteral("instruction_data")).toArray();
    words.append(-1);
    message.insert(QStringLiteral("instruction_data"), words);
    publicTransaction.insert(QStringLiteral("message"), message);
    transaction.insert(QStringLiteral("Public"), publicTransaction);
    list = QJsonArray{};
    list.append(transaction);
    LOGOS_ASSERT_FALSE(PalaceLezCodec::parseFinalizedTransactions(
        QJsonDocument(list).toJson(QJsonDocument::Compact).toStdString()).accepted);

    LOGOS_ASSERT_TRUE(PalaceLezCodec::parseFinalizedTransactions(
        indexerRpcJson({{plan, hash(0U)}})).accepted);

    transaction = indexerTransaction(plan, hash(0U));
    publicTransaction = transaction.value(QStringLiteral("Public")).toObject();
    QJsonObject witness =
        publicTransaction.value(QStringLiteral("witness_set")).toObject();
    QJsonArray signatures =
        witness.value(QStringLiteral("signatures_and_public_keys")).toArray();
    QJsonArray pair = signatures.at(0).toArray();
    pair.replace(1, QStringLiteral("not-base64"));
    signatures.replace(0, pair);
    witness.insert(QStringLiteral("signatures_and_public_keys"), signatures);
    publicTransaction.insert(QStringLiteral("witness_set"), witness);
    transaction.insert(QStringLiteral("Public"), publicTransaction);
    list = QJsonArray{};
    list.append(transaction);
    LOGOS_ASSERT_FALSE(PalaceLezCodec::parseFinalizedTransactions(
        QJsonDocument(list).toJson(QJsonDocument::Compact).toStdString()).accepted);

    transaction = indexerTransaction(plan, hash(0U));
    publicTransaction = transaction.value(QStringLiteral("Public")).toObject();
    message = publicTransaction.value(QStringLiteral("message")).toObject();
    QJsonArray nonces = message.value(QStringLiteral("nonces")).toArray();
    nonces.replace(0, 9007199254740992.0);
    message.insert(QStringLiteral("nonces"), nonces);
    publicTransaction.insert(QStringLiteral("message"), message);
    transaction.insert(QStringLiteral("Public"), publicTransaction);
    list = QJsonArray{};
    list.append(transaction);
    LOGOS_ASSERT_FALSE(PalaceLezCodec::parseFinalizedTransactions(
        QJsonDocument(list).toJson(QJsonDocument::Compact).toStdString()).accepted);

    const std::string legacyFlattened =
        "[{\"hash\":\"" + hash(0U)
        + "\",\"program_id\":\"" + std::string(kProgramId)
        + "\",\"accounts\":[],\"instruction_words\":[],\"signature_count\":1}]";
    LOGOS_ASSERT_FALSE(
        PalaceLezCodec::parseFinalizedTransactions(legacyFlattened).accepted);

    QJsonObject privateTransaction;
    privateTransaction.insert(QStringLiteral("Private"), QJsonObject{});
    list = QJsonArray{};
    list.append(privateTransaction);
    LOGOS_ASSERT_FALSE(PalaceLezCodec::parseFinalizedTransactions(
        QJsonDocument(list).toJson(QJsonDocument::Compact).toStdString()).accepted);
}

LOGOS_TEST(palace_lez_parses_only_canonical_positive_ordered_action_ids) {
    std::uint64_t value = 0;
    LOGOS_ASSERT_TRUE(palace::PalaceLezCodec::parseOrderedActionId("1", value));
    LOGOS_ASSERT_EQ(value, 1U);
    LOGOS_ASSERT_TRUE(palace::PalaceLezCodec::parseOrderedActionId(
        "18446744073709551615", value));
    LOGOS_ASSERT_EQ(value, UINT64_MAX);
    LOGOS_ASSERT_FALSE(palace::PalaceLezCodec::parseOrderedActionId("0", value));
    LOGOS_ASSERT_FALSE(palace::PalaceLezCodec::parseOrderedActionId("01", value));
    LOGOS_ASSERT_FALSE(palace::PalaceLezCodec::parseOrderedActionId("+1", value));
    LOGOS_ASSERT_FALSE(palace::PalaceLezCodec::parseOrderedActionId(
        "18446744073709551616", value));
}

#include "test_lez_coordinator.inc"
